In [79]:
import numpy as np
import pandas as pd

In [80]:
dataset=pd.read_csv(r"C:\Users\Venu\Downloads\Fish.csv")

In [81]:
dataset.head(10)

  Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
5   Bream   450.0     26.8     29.7     34.7  13.6024  4.9274
6   Bream   500.0     26.8     29.7     34.5  14.1795  5.2785
7   Bream   390.0     27.6     30.0     35.0  12.6700  4.6900
8   Bream   450.0     27.6     30.0     35.1  14.0049  4.8438
9   Bream   500.0     28.5     30.7     36.2  14.2266  4.9594

In [82]:
dataset.isnull().any()

Species    False
Weight     False
Length1    False
Length2    False
Length3    False
Height     False
Width      False
dtype: bool

In [83]:
x=dataset.iloc[:,2:7].values
y=dataset.iloc[:,1].values

In [84]:
x.shape

(159, 5)

In [85]:
y.shape

(159,)

In [86]:
x

array([[23.2   , 25.4   , 30.    , 11.52  ,  4.02  ],
       [24.    , 26.3   , 31.2   , 12.48  ,  4.3056],
       [23.9   , 26.5   , 31.1   , 12.3778,  4.6961],
       [26.3   , 29.    , 33.5   , 12.73  ,  4.4555],
       [26.5   , 29.    , 34.    , 12.444 ,  5.134 ],
       [26.8   , 29.7   , 34.7   , 13.6024,  4.9274],
       [26.8   , 29.7   , 34.5   , 14.1795,  5.2785],
       [27.6   , 30.    , 35.    , 12.67  ,  4.69  ],
       [27.6   , 30.    , 35.1   , 14.0049,  4.8438],
       [28.5   , 30.7   , 36.2   , 14.2266,  4.9594],
       [28.4   , 31.    , 36.2   , 14.2628,  5.1042],
       [28.7   , 31.    , 36.2   , 14.3714,  4.8146],
       [29.1   , 31.5   , 36.4   , 13.7592,  4.368 ],
       [29.5   , 32.    , 37.3   , 13.9129,  5.0728],
       [29.4   , 32.    , 37.2   , 14.9544,  5.1708],
       [29.4   , 32.    , 37.2   , 15.438 ,  5.58  ],
       [30.4   , 33.    , 38.3   , 14.8604,  5.2854],
       [30.4   , 33.    , 38.5   , 14.938 ,  5.1975],
       [30.9   , 33.5   , 38.6   , 15.633 ,  5.1338],
       [31.    , 33.5   , 38.7   , 14.4738,  5.7276],
       [31.3   , 34.    , 39.5   , 15.1285,  5.5695],
       [31.4   , 34.    , 39.2   , 15.9936,  5.3704],
       [31.5   , 34.5   , 39.7   , 15.5227,  5.2801],
       [31.8   , 35.    , 40.6   , 15.4686,  6.1306],
       [31.9   , 35.    , 40.5   , 16.2405,  5.589 ],
       [31.8   , 35.    , 40.9   , 16.36  ,  6.0532],
       [32.    , 35.    , 40.6   , 16.3618,  6.09  ],
       [32.7   , 36.    , 41.5   , 16.517 ,  5.8515],
       [32.8   , 36.    , 41.6   , 16.8896,  6.1984],
       [33.5   , 37.    , 42.6   , 18.957 ,  6.603 ],
       [35.    , 38.5   , 44.1   , 18.0369,  6.3063],
       [35.    , 38.5   , 44.    , 18.084 ,  6.292 ],
       [36.2   , 39.5   , 45.3   , 18.7542,  6.7497],
       [37.4   , 41.    , 45.9   , 18.6354,  6.7473],
       [38.    , 41.    , 46.5   , 17.6235,  6.3705],
       [12.9   , 14.1   , 16.2   ,  4.1472,  2.268 ],
       [16.5   , 18.2   , 20.3   ,  5.2983,  2.8217],
       [17.5   , 18.8   , 21.2   ,  5.5756,  2.9044],
       [18.2   , 19.8   , 22.2   ,  5.6166,  3.1746],
       [18.6   , 20.    , 22.2   ,  6.216 ,  3.5742],
       [19.    , 20.5   , 22.8   ,  6.4752,  3.3516],
       [19.1   , 20.8   , 23.1   ,  6.1677,  3.3957],
       [19.4   , 21.    , 23.7   ,  6.1146,  3.2943],
       [20.4   , 22.    , 24.7   ,  5.8045,  3.7544],
       [20.5   , 22.    , 24.3   ,  6.6339,  3.5478],
       [20.5   , 22.5   , 25.3   ,  7.0334,  3.8203],
       [21.    , 22.5   , 25.    ,  6.55  ,  3.325 ],
       [21.1   , 22.5   , 25.    ,  6.4   ,  3.8   ],
       [22.    , 24.    , 27.2   ,  7.5344,  3.8352],
       [22.    , 23.4   , 26.7   ,  6.9153,  3.6312],
       [22.1   , 23.5   , 26.8   ,  7.3968,  4.1272],
       [23.6   , 25.2   , 27.9   ,  7.0866,  3.906 ],
       [24.    , 26.    , 29.2   ,  8.8768,  4.4968],
       [25.    , 27.    , 30.6   ,  8.568 ,  4.7736],
       [29.5   , 31.7   , 35.    ,  9.485 ,  5.355 ],
       [23.6   , 26.    , 28.7   ,  8.3804,  4.2476],
       [24.1   , 26.5   , 29.3   ,  8.1454,  4.2485],
       [25.6   , 28.    , 30.8   ,  8.778 ,  4.6816],
       [28.5   , 31.    , 34.    , 10.744 ,  6.562 ],
       [33.7   , 36.4   , 39.6   , 11.7612,  6.5736],
       [37.3   , 40.    , 43.5   , 12.354 ,  6.525 ],
       [13.5   , 14.7   , 16.5   ,  6.8475,  2.3265],
       [14.3   , 15.5   , 17.4   ,  6.5772,  2.3142],
       [16.3   , 17.7   , 19.8   ,  7.4052,  2.673 ],
       [17.5   , 19.    , 21.3   ,  8.3922,  2.9181],
       [18.4   , 20.    , 22.4   ,  8.8928,  3.2928],
       [19.    , 20.7   , 23.2   ,  8.5376,  3.2944],
       [19.    , 20.7   , 23.2   ,  9.396 ,  3.4104],
       [19.8   , 21.5   , 24.1   ,  9.7364,  3.1571],
       [21.2   , 23.    , 25.8   , 10.3458,  3.6636],
       [23.    , 25.    , 28.    , 11.088 ,  4.144 ],
       [24.    , 26.    , 29.    , 11.368 ,  4.234 ],
       [ 7.5   ,  8.4   ,  8.8   ,  2.112 ,  1.408 ],
       [12.5   , 13.7   , 14.7   ,  3.528 ,  1.9992],
       [13.8   , 15.    , 16.    ,  3.824 ,  2.432 ],
       [15.    , 16.2   , 17.2   ,  4.5924,  2.6316],
       [15.7   , 17.4   , 18.5   ,  4.588 ,  2.9415],
       [16.2   , 18.    , 19.2   ,  5.2224,  3.3216],
       [16.8   , 18.7   , 19.4   ,  5.1992,  3.1234],
       [17.2   , 19.    , 20.2   ,  5.6358,  3.0502],
       [17.8   , 19.6   , 20.8   ,  5.1376,  3.0368],
       [18.2   , 20.    , 21.    ,  5.082 ,  2.772 ],
       [19.    , 21.    , 22.5   ,  5.6925,  3.555 ],
       [19.    , 21.    , 22.5   ,  5.9175,  3.3075],
       [19.    , 21.    , 22.5   ,  5.6925,  3.6675],
       [19.3   , 21.3   , 22.8   ,  6.384 ,  3.534 ],
       [20.    , 22.    , 23.5   ,  6.11  ,  3.4075],
       [20.    , 22.    , 23.5   ,  5.64  ,  3.525 ],
       [20.    , 22.    , 23.5   ,  6.11  ,  3.525 ],
       [20.    , 22.    , 23.5   ,  5.875 ,  3.525 ],
       [20.    , 22.    , 23.5   ,  5.5225,  3.995 ],
       [20.5   , 22.5   , 24.    ,  5.856 ,  3.624 ],
       [20.5   , 22.5   , 24.    ,  6.792 ,  3.624 ],
       [20.7   , 22.7   , 24.2   ,  5.9532,  3.63  ],
       [21.    , 23.    , 24.5   ,  5.2185,  3.626 ],
       [21.5   , 23.5   , 25.    ,  6.275 ,  3.725 ],
       [22.    , 24.    , 25.5   ,  7.293 ,  3.723 ],
       [22.    , 24.    , 25.5   ,  6.375 ,  3.825 ],
       [22.6   , 24.6   , 26.2   ,  6.7334,  4.1658],
       [23.    , 25.    , 26.5   ,  6.4395,  3.6835],
       [23.5   , 25.6   , 27.    ,  6.561 ,  4.239 ],
       [25.    , 26.5   , 28.    ,  7.168 ,  4.144 ],
       [25.2   , 27.3   , 28.7   ,  8.323 ,  5.1373],
       [25.4   , 27.5   , 28.9   ,  7.1672,  4.335 ],
       [25.4   , 27.5   , 28.9   ,  7.0516,  4.335 ],
       [25.4   , 27.5   , 28.9   ,  7.2828,  4.5662],
       [25.9   , 28.    , 29.4   ,  7.8204,  4.2042],
       [26.9   , 28.7   , 30.1   ,  7.5852,  4.6354],
       [27.8   , 30.    , 31.6   ,  7.6156,  4.7716],
       [30.5   , 32.8   , 34.    , 10.03  ,  6.018 ],
       [32.    , 34.5   , 36.5   , 10.2565,  6.3875],
       [32.5   , 35.    , 37.3   , 11.4884,  7.7957],
       [34.    , 36.5   , 39.    , 10.881 ,  6.864 ],
       [34.    , 36.    , 38.3   , 10.6091,  6.7408],
       [34.5   , 37.    , 39.4   , 10.835 ,  6.2646],
       [34.6   , 37.    , 39.3   , 10.5717,  6.3666],
       [36.5   , 39.    , 41.4   , 11.1366,  7.4934],
       [36.5   , 39.    , 41.4   , 11.1366,  6.003 ],
       [36.6   , 39.    , 41.3   , 12.4313,  7.3514],
       [36.9   , 40.    , 42.3   , 11.9286,  7.1064],
       [37.    , 40.    , 42.5   , 11.73  ,  7.225 ],
       [37.    , 40.    , 42.4   , 12.3808,  7.4624],
       [37.1   , 40.    , 42.5   , 11.135 ,  6.63  ],
       [39.    , 42.    , 44.6   , 12.8002,  6.8684],
       [39.8   , 43.    , 45.2   , 11.9328,  7.2772],
       [40.1   , 43.    , 45.5   , 12.5125,  7.4165],
       [40.2   , 43.5   , 46.    , 12.604 ,  8.142 ],
       [41.1   , 44.    , 46.6   , 12.4888,  7.5958],
       [30.    , 32.3   , 34.8   ,  5.568 ,  3.3756],
       [31.7   , 34.    , 37.8   ,  5.7078,  4.158 ],
       [32.7   , 35.    , 38.8   ,  5.9364,  4.3844],
       [34.8   , 37.3   , 39.8   ,  6.2884,  4.0198],
       [35.5   , 38.    , 40.5   ,  7.29  ,  4.5765],
       [36.    , 38.5   , 41.    ,  6.396 ,  3.977 ],
       [40.    , 42.5   , 45.5   ,  7.28  ,  4.3225],
       [40.    , 42.5   , 45.5   ,  6.825 ,  4.459 ],
       [40.1   , 43.    , 45.8   ,  7.786 ,  5.1296],
       [42.    , 45.    , 48.    ,  6.96  ,  4.896 ],
       [43.2   , 46.    , 48.7   ,  7.792 ,  4.87  ],
       [44.8   , 48.    , 51.2   ,  7.68  ,  5.376 ],
       [48.3   , 51.7   , 55.1   ,  8.9262,  6.1712],
       [52.    , 56.    , 59.7   , 10.6863,  6.9849],
       [56.    , 60.    , 64.    ,  9.6   ,  6.144 ],
       [56.    , 60.    , 64.    ,  9.6   ,  6.144 ],
       [59.    , 63.4   , 68.    , 10.812 ,  7.48  ],
       [ 9.3   ,  9.8   , 10.8   ,  1.7388,  1.0476],
       [10.    , 10.5   , 11.6   ,  1.972 ,  1.16  ],
       [10.1   , 10.6   , 11.6   ,  1.7284,  1.1484],
       [10.4   , 11.    , 12.    ,  2.196 ,  1.38  ],
       [10.7   , 11.2   , 12.4   ,  2.0832,  1.2772],
       [10.8   , 11.3   , 12.6   ,  1.9782,  1.2852],
       [11.3   , 11.8   , 13.1   ,  2.2139,  1.2838],
       [11.3   , 11.8   , 13.1   ,  2.2139,  1.1659],
       [11.4   , 12.    , 13.2   ,  2.2044,  1.1484],
       [11.5   , 12.2   , 13.4   ,  2.0904,  1.3936],
       [11.7   , 12.4   , 13.5   ,  2.43  ,  1.269 ],
       [12.1   , 13.    , 13.8   ,  2.277 ,  1.2558],
       [13.2   , 14.3   , 15.2   ,  2.8728,  2.0672],
       [13.8   , 15.    , 16.2   ,  2.9322,  1.8792]])

In [87]:
y

array([ 242. ,  290. ,  340. ,  363. ,  430. ,  450. ,  500. ,  390. ,
        450. ,  500. ,  475. ,  500. ,  500. ,  340. ,  600. ,  600. ,
        700. ,  700. ,  610. ,  650. ,  575. ,  685. ,  620. ,  680. ,
        700. ,  725. ,  720. ,  714. ,  850. , 1000. ,  920. ,  955. ,
        925. ,  975. ,  950. ,   40. ,   69. ,   78. ,   87. ,  120. ,
          0. ,  110. ,  120. ,  150. ,  145. ,  160. ,  140. ,  160. ,
        169. ,  161. ,  200. ,  180. ,  290. ,  272. ,  390. ,  270. ,
        270. ,  306. ,  540. ,  800. , 1000. ,   55. ,   60. ,   90. ,
        120. ,  150. ,  140. ,  170. ,  145. ,  200. ,  273. ,  300. ,
          5.9,   32. ,   40. ,   51.5,   70. ,  100. ,   78. ,   80. ,
         85. ,   85. ,  110. ,  115. ,  125. ,  130. ,  120. ,  120. ,
        130. ,  135. ,  110. ,  130. ,  150. ,  145. ,  150. ,  170. ,
        225. ,  145. ,  188. ,  180. ,  197. ,  218. ,  300. ,  260. ,
        265. ,  250. ,  250. ,  300. ,  320. ,  514. ,  556. ,  840. ,
        685. ,  700. ,  700. ,  690. ,  900. ,  650. ,  820. ,  850. ,
        900. , 1015. ,  820. , 1100. , 1000. , 1100. , 1000. , 1000. ,
        200. ,  300. ,  300. ,  300. ,  430. ,  345. ,  456. ,  510. ,
        540. ,  500. ,  567. ,  770. ,  950. , 1250. , 1600. , 1550. ,
       1650. ,    6.7,    7.5,    7. ,    9.7,    9.8,    8.7,   10. ,
          9.9,    9.8,   12.2,   13.4,   12.2,   19.7,   19.9])

In [88]:
dataset.head()

  Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [89]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state =47)

In [90]:
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [91]:
ypred=mlr.predict(x_test)

In [92]:
ypred

array([ 371.28037914,   79.11332804,  270.6640393 ,  -90.71790904,
        816.89255419,  193.95767127,  614.54114501, -211.14188538,
        629.1956673 ,  590.00194183,  785.31916849, -234.92451459,
        440.67430075,  471.25079606,  134.62941993, -100.14511042,
        126.31605893,  204.20581184,  659.16842573,  413.67579331,
        272.65895413,  506.97223465,  210.20685739,   19.69326077,
         70.0586269 ,   10.99294675,  714.88342612,  413.46546667,
        821.72326996,  136.04422301,  542.69374811,  328.01714997])

In [93]:
y_test

array([290. ,  78. , 180. ,  19.7, 900. , 145. , 600. ,   7. , 514. ,
       345. , 650. ,   6.7, 300. , 450. , 120. ,  40. , 120. , 160. ,
       610. , 300. , 188. , 390. , 150. ,  70. ,  78. ,  55. , 840. ,
       300. , 850. , 115. , 475. , 242. ])

In [94]:
from sklearn.metrics import r2_score
accuracy = r2_score(ypred,y_test)

In [95]:
accuracy

0.869523155213493

In [96]:
dataset.head()

  Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [97]:
yp=mlr.predict([[23.2,25.4,30.0,11.5200,4.30200]])

In [78]:
yp

array([332.42342797])